name: Mirror to Codeberg

on:
  push:
    branches: [ main, master ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Codeberg
        uses: yesolutions/mirror-repository@v1
        with:
          source_repo: ${{ github.repository }}
          target_repo: https://codeberg.org/koolremhaas/operationnotvarp.git
          target_token: ${{ secrets.CODEBERG_TOKEN }}
