name: Mirror to Codeberg

on:
  push:
    branches: [ main, master ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # ← Detta var det som saknades!
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Behövs för att mirror ska fungera bra

      - name: Mirror to Codeberg
        uses: cssnr/mirror-repository-action@v1
        with:
          host: https://codeberg.org
          username: koolremhaas
          repo: operationnotvarp
          password: ${{ secrets.CODEBERG_TOKEN }}
          create: true
